name: daily-fortune
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1 libasound2t64  # 최신 우분투 버전 대응
          
      - name: Install Python Packages
        run: pip install requests playwright
        
      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python fortune_telegram_bot.py
